CoTServicePort: 8087
SSLCoTServicePort: 8089
DataPackageServiceDefaultIP: '0.0.0.0'
UserConnectionIP: '0.0.0.0'
APIPort: 19023
FederationPort: 9000
APIIP: '0.0.0.0'
SaveCoTToDB: True
DBFilePath: 'C:\\python\\Lib\\site-packages\\FreeTAKServer\\FTSDataBase.db'
MainPath: 'C:\\python\\Lib\\site-packages\\FreeTAKServer'
CertsPath: 'C:\\python\\Lib\\site-packages\\FreeTAKServer\\certs'

