CoTServicePort: 8087
SSLCoTServicePort: 8089
DataPackageServiceDefaultIP: '0.0.0.0'
UserConnectionIP: '0.0.0.0'
APIPort: 19023
FederationPort: 9000
APIIP: '0.0.0.0'
SaveCoTToDB: True
DBFilePath: '/opt/fts/FTSDataBase.db'
MainPath: '/usr/local/lib/python3.8/dist-packages/FreeTAKServer'
CertsPath: '/opt/fts/certs'

